name: local_basket
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  dio: ^5.7.0
  pinput: ^5.0.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  internet_connection_checker_plus: ^2.5.2
  get_it: ^8.0.0
  connectivity_plus: ^6.1.3
  permission_handler: ^11.4.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_svg: ^2.0.9
  table_calendar: ^3.0.8
  intl: ^0.20.2
  file_picker: ^9.0.0
  pdfx: ^2.8.0
  flutter_pdfview: ^1.4.0
  google_fonts: ^6.1.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  speech_to_text: ^7.0.0
  google_maps_flutter: ^2.12.2
  modal_bottom_sheet: ^3.0.0
  razorpay_flutter: ^1.3.5
  timeline_tile: ^2.0.0
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  sqflite: ^2.3.2
  shimmer: ^3.0.0
  carousel_slider: ^5.1.1
  video_player: ^2.10.0
  device_info_plus: ^11.5.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/png/ic_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/jpg/
    - assets/images/png/
    - assets/images/avif/
    - assets/images/videos/

