// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJQiR5Dhte_GlznjW-8bxttpHD2VrE6Uk',
    appId: '1:351201490110:web:793771e0ddbcaf428e9aef',
    messagingSenderId: '351201490110',
    projectId: 'localbasket-fe25e',
    authDomain: 'localbasket-fe25e.firebaseapp.com',
    storageBucket: 'localbasket-fe25e.firebasestorage.app',
    measurementId: 'G-GD10W9TNNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC__hdOF5Z-piCmVfqL-sRWlkQ_44Nv3FI',
    appId: '1:351201490110:android:92d106832416d4498e9aef',
    messagingSenderId: '351201490110',
    projectId: 'localbasket-fe25e',
    storageBucket: 'localbasket-fe25e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1iWrM1iY-e_QvL95E0vq1N_QE0jC-JTw',
    appId: '1:351201490110:ios:a2a221e829638a478e9aef',
    messagingSenderId: '351201490110',
    projectId: 'localbasket-fe25e',
    storageBucket: 'localbasket-fe25e.firebasestorage.app',
    iosBundleId: 'com.localbaskethd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1iWrM1iY-e_QvL95E0vq1N_QE0jC-JTw',
    appId: '1:351201490110:ios:e73ff498235de23a8e9aef',
    messagingSenderId: '351201490110',
    projectId: 'localbasket-fe25e',
    storageBucket: 'localbasket-fe25e.firebasestorage.app',
    iosBundleId: 'com.example.localBasket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJQiR5Dhte_GlznjW-8bxttpHD2VrE6Uk',
    appId: '1:351201490110:web:1c7d1a63049386698e9aef',
    messagingSenderId: '351201490110',
    projectId: 'localbasket-fe25e',
    authDomain: 'localbasket-fe25e.firebaseapp.com',
    storageBucket: 'localbasket-fe25e.firebasestorage.app',
    measurementId: 'G-DWL8GT8XJ5',
  );
}
