// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpALyil1LnDaW97H_GzF-4dG-wbNzSNBo',
    appId: '1:1052044920208:web:8fa89fc56cd796aba35f15',
    messagingSenderId: '1052044920208',
    projectId: 'local_basket-fd2c1',
    authDomain: 'local_basket-fd2c1.firebaseapp.com',
    storageBucket: 'local_basket-fd2c1.firebasestorage.app',
    measurementId: 'G-JVYQ74MZP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqTgtzwSq-aCwpziqmom-djWA0asxY8HU',
    appId: '1:1052044920208:android:020c186cc2863d05a35f15',
    messagingSenderId: '1052044920208',
    projectId: 'local_basket-fd2c1',
    storageBucket: 'local_basket-fd2c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZWrpfgzAIHO0fPWhh3M15SwQ_3LjPLy8',
    appId: '1:1052044920208:ios:199b06ff822d62e5a35f15',
    messagingSenderId: '1052044920208',
    projectId: 'local_basket-fd2c1',
    storageBucket: 'local_basket-fd2c1.firebasestorage.app',
    iosBundleId: 'com.hlt.local_basket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZWrpfgzAIHO0fPWhh3M15SwQ_3LjPLy8',
    appId: '1:1052044920208:ios:199b06ff822d62e5a35f15',
    messagingSenderId: '1052044920208',
    projectId: 'local_basket-fd2c1',
    storageBucket: 'local_basket-fd2c1.firebasestorage.app',
    iosBundleId: 'com.hlt.local_basket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpALyil1LnDaW97H_GzF-4dG-wbNzSNBo',
    appId: '1:1052044920208:web:38b1f1026d26ec55a35f15',
    messagingSenderId: '1052044920208',
    projectId: 'local_basket-fd2c1',
    authDomain: 'local_basket-fd2c1.firebaseapp.com',
    storageBucket: 'local_basket-fd2c1.firebasestorage.app',
    measurementId: 'G-QVTBTKDJ22',
  );
}
